export const START_GETTING_LOCATION = "START_GETTING_LOCATION";
export const ERROR_IN_GETTING_LOCATION = "ERROR_IN_GETTING_LOCATION";

export const SAVE_LOCATION_AND_ADDRESS = "SAVE_LOCATION_AND_ADDRESS";
export const SAVE_LOCATION_ADDRESS = "SAVE_LOCATION_ADDRESS";
export const SAVE_LOCATION_COORDINATES = "SAVE_LOCATION_COORDINATES";

export const SAVE_LOCATION_ALL_ADDRESS = "SAVE_LOCATION_ALL_ADDRESS";
export const START_GETTING_ALL_LOCATIONS = "START_GETTING_ALL_LOCATIONS";
export const ERROR_IN_GETTING_ALL_LOCATIONS = "ERROR_IN_GETTING_ALL_LOCATIONS";
