export const START_GETTING_ORDERS = "START_GETTING_ORDERS";
export const SAVE_ORDERS = "SAVE_ORDERS";
export const ERROR_IN_GETTING_ORDERS = "ERROR_IN_GETTING_ORDERS";

export const START_GETTING_ORDER_BY_ID = "START_GETTING_ORDER_BY_ID";
export const SAVE_ORDER_BY_ID = "SAVE_ORDER_BY_ID";
export const SAVE_ORDER_IMAGE_URL = "SAVE_ORDER_IMAGE_URL";
export const SAVE_ORDER_VOICE_NOTE_URL = "SAVE_ORDER_VOICE_NOTE_URL";
export const ERROR_IN_GETTING_ORDER_BY_ID = "ERROR_IN_GETTING_ORDER_BY_ID";

export const CANCELLED_ORDER_BY_ID = "CANCELLED_ORDER_BY_ID";
export const EMPTY_ORDER_BY_ID_REDUCER = "EMPTY_ORDER_BY_ID_REDUCER";
