export const START_GETTING_USER_DASHBOARD_DATA = 'START_GETTING_USER_DASHBOARD_DATA'
export const ERROR_IN_GETTING_USER_DASHBOARD_DATA = 'ERROR_IN_GETTING_USER_DASHBOARD_DATA'

export const SAVE_USER_DASHBOARD_DATA = 'SAVE_USER_DASHBOARD_DATA'
